version: '2'
services:
  nginx:
      image: nginx
      ports: 
        - "80:80"
      container_name: "nginx"
      volumes: 
        - /home/nginx/www:/usr/share/nginx/html
        - /home/nginx/logs:/var/log/nginx
        - /home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - /home/nginx/conf/conf.d:/etc/nginx/conf.d
        - /etc/localtime:/etc/localtime
      depends_on: 
        - tomcat8027
        - tomcat8028
  tomcat8027:
      image: tomcat
      ports: 
        - "8027:8080"
      container_name: "tomcat8027"
      volumes:
        - /home/tomcat8027/webapps:/usr/local/tomcat/webapps
        - /home/tomcat8027/logs:/usr/local/tomcat/logs 
        - /etc/localtime:/etc/localtime
  tomcat8028:
      image: tomcat
      ports: 
        - "8028:8080"
      container_name: "tomcat8028"
      volumes:
        - /home/tomcat8028/webapps:/usr/local/tomcat/webapps
        - /home/tomcat8028/logs:/usr/local/tomcat/logs
        - /etc/localtime:/etc/localtime

